### ISSUE TITLE
Edge image issue with yarn v2

### ISSUE THREAD

**Issue by timmo001** [timmo001/home-panel#1196]
# Description

Error with built image for edge. Produces this error on run:

```
home-panel_1  | Run Home Panel..
home-panel_1  | /opt/panel/.pnp.js:30419
home-panel_1  |     throw firstError;
home-panel_1  |     ^
home-panel_1  | 
home-panel_1  | Error: Qualified path resolution failed - none of the candidates can be found on the disk.
home-panel_1  | 
home-panel_1  | Source path: /opt/panel/backend/lib
home-panel_1  | Rejected candidate: /opt/panel/backend/lib
home-panel_1  | Rejected candidate: /opt/panel/backend/lib.js
home-panel_1  | Rejected candidate: /opt/panel/backend/lib.json
home-panel_1  | Rejected candidate: /opt/panel/backend/lib.node
home-panel_1  | 
home-panel_1  |     at internalTools_makeError (/opt/panel/.pnp.js:30166:34)
home-panel_1  |     at resolveUnqualified (/opt/panel/.pnp.js:31158:13)
home-panel_1  |     at resolveRequest (/opt/panel/.pnp.js:31182:14)
home-panel_1  |     at Object.resolveRequest (/opt/panel/.pnp.js:31242:26)
home-panel_1  |     at Function.external_module_.Module._resolveFilename (/opt/panel/.pnp.js:30396:34)
home-panel_1  |     at Function.external_module_.Module._load (/opt/panel/.pnp.js:30262:51)
home-panel_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
home-panel_1  |     at internal/main/run_main_module.js:17:47
```

## How to reproduce the issue (if applicable)

Run the timmo001/home-panel:edge

**Comment by timmo001** [comment]
Issue resolved. Was due to new setup with yarn v2 and workspaces
